name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/church-App/Testing-CI-CD
            git pull origin main

            # Backend
            cd backend
            npm install
            pm2 restart backend || pm2 start index.js --name backend
            pm2 save

            # Frontend
            cd ../frontend
            npm install
            npm run build

            # Deploy frontend
            sudo rm -rf /var/www/church-frontend/*
            sudo cp -r build/* /var/www/church-frontend/

            sudo systemctl restart nginx

